export const AUTHENTICATION_USER = 'AUTHENTICATION_USER';
export const CATCH_ERRORS = 'CATCH_ERRORS';
export const GET_DASHBOARD = 'GET_DASHBOARD';
export const RESET = 'RESET';
export const RESTART_SYSTEM = 'RESTART_SYSTEM';

export const GET_COINS = 'GET_COINS';
export const GET_CURRENCY = 'GET_CURRENCY';
export const GET_COINS_WITH_CURRENCY = 'GET_COINS_WITH_CURRENCY';
export const GET_MAIN_COINS = 'GET_MAIN_COINS';
export const GET_MIDNIGHT_COINS = 'GET_MIDNIGHT_COINS';

export const COINS_LIST = 'COINS_LIST';
export const CREATE_COIN = 'CREATE_COIN';
export const SHOW_COIN = 'SHOW_COIN';
export const EDIT_COIN = 'EDIT_COIN';
export const DELETE_COIN = 'DELETE_COIN';

export const COINS_FORMAT_LIST = 'COINS_FORMAT_LIST';
export const CREATE_COIN_FORMAT = 'CREATE_COIN_FORMAT';
export const SHOW_COIN_FORMAT = 'SHOW_COIN_FORMAT';
export const EDIT_COIN_FORMAT = 'EDIT_COIN_FORMAT';
export const DELETE_COIN_FORMAT = 'DELETE_COIN_FORMAT';

export const USERS_LIST = 'USERS_LIST';
export const CREATE_USER = 'CREATE_USER';
export const SHOW_USER = 'SHOW_USER';
export const EDIT_USER = 'EDIT_USER';
export const DELETE_USER = 'DELETE_USER';
export const SEND_CONFIRM_EMAIL_TO_USER = 'SEND_CONFIRM_EMAIL_TO_USER';
export const SEND_EMAIL_ACTIVATION_TO_USER = 'SEND_EMAIL_ACTIVATION_TO_USER';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const LATEST_NOTIFICATIONS = 'LATEST_NOTIFICATIONS';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';

export const GET_PAYMENTS = 'GET_PAYMENTS';
export const LATEST_PAYMENTS = 'LATEST_PAYMENTS';
export const SHOW_PAYMENT = 'SHOW_PAYMENT';
export const DELETE_PAYMENT = 'DELETE_PAYMENT';

export const GET_LOGS = 'GET_LOGS';
export const LATEST_LOGS = 'LATEST_LOGS';
export const SHOW_LOG = 'SHOW_LOG';
export const DELETE_LOG = 'DELETE_LOG';
