export const AUTHENTICATION_USER = 'AUTHENTICATION_USER';
export const LOGIN_USER_SUCCESSFUL = 'LOGIN_USER_SUCCESSFUL';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const AUTHENTICATION_EMAIL_ACTIVATION = 'AUTHENTICATION_EMAIL_ACTIVATION';

export const CATCH_ERRORS = 'CATCH_ERRORS';
export const GET_DASHBOARD = 'GET_DASHBOARD';

export const GET_COINS = 'GET_COINS';
export const GET_COINS_FORMAT = 'GET_COINS_FORMAT';
export const GET_COINS_HISTORY = 'GET_COINS_HISTORY';

export const UPDATE_USER_ACCOUNT = 'UPDATE_USER_ACCOUNT';
export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';
export const SEND_EMAIL_FOR_ACTIVATION = 'SEND_EMAIL_FOR_ACTIVATION';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_MORE_NOTIFICATIONS = 'GET_MORE_NOTIFICATIONS';
export const LATEST_NOTIFICATIONS = 'LATEST_NOTIFICATIONS';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';

export const GET_PAYMENTS = 'GET_PAYMENTS';
export const DO_PAYMENT = 'DO_PAYMENT';
